import React, { useState } from 'react';
import {
  Sparkles,
  Bot,
  AlertTriangle,
  CheckCircle2,
  HelpCircle,
  ArrowRight,
  RefreshCw,
  X,
  PhoneCall,
  Shield,
  FileText,
  Send,
  Check,
} from 'lucide-react';

interface AiCaseCategoryAssistantProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirmCategory: (category: string, incidentStatement: string, aiSummary: string) => void;
  currentCategory?: string;
}

interface QuestionDef {
  id: string;
  question: string;
  options: string[];
}

interface AnalysisResult {
  category: string;
  isEmergency: boolean;
  confidence: number;
  ipcSection: string;
  bnsSection: string;
  explanation: string;
  statement: string;
  qaSummary: { question: string; answer: string }[];
}

export const AiCaseCategoryAssistant: React.FC<AiCaseCategoryAssistantProps> = ({
  isOpen,
  onClose,
  onConfirmCategory,
  currentCategory,
}) => {
  // Wizard steps: 'input' -> 'clarifying' -> 'result'
  const [step, setStep] = useState<'input' | 'clarifying' | 'result'>('input');
  const [clarificationRound, setClarificationRound] = useState<number>(1);
  const [recordedQa, setRecordedQa] = useState<{ question: string; answer: string }[]>([]);
  const [statement, setStatement] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  // Dynamic questions generated by AI
  const [questions, setQuestions] = useState<QuestionDef[]>([]);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [customAnswerInput, setCustomAnswerInput] = useState<Record<string, string>>({});

  // Result state
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);

  if (!isOpen) return null;

  // Sample quick statements for user convenience
  const sampleStatements = [
    'I am a college student and seniors are forcing me to do humiliating things in the hostel',
    'A saw a person who kill the another person Infront of me',
    'Someone sent a fraudulent link and transferred ₹45,000 from my bank',
    'My smartphone was snatched by two persons on a motorcycle',
    'Our house lock was broken while we were away and gold jewelry was stolen',
  ];

  // Helper to detect initial domain and build relevant clarifying questions
  const generateQuestionsForStatement = (text: string): { questions: QuestionDef[]; immediateResult?: AnalysisResult } => {
    const lower = text.toLowerCase();

    // 1. Homicide / Killing / Death / Violent Attack
    if (
      lower.includes('kill') ||
      lower.includes('murder') ||
      lower.includes('dead') ||
      lower.includes('stab') ||
      lower.includes('shot') ||
      lower.includes('shoot') ||
      lower.includes('homicide') ||
      lower.includes('blood') ||
      lower.includes('corpse') ||
      lower.includes('body')
    ) {
      return {
        questions: [
          {
            id: 'death_status',
            question: 'Does the another person die?',
            options: [
              'Yes, the person died / succumbed to injuries on the spot',
              'No, the person survived / is undergoing emergency medical care',
              'Not sure / person was unresponsive and bleeding heavily',
            ],
          },
          {
            id: 'weapon_used',
            question: 'By which tool or weapon did the person attack or kill that another person?',
            options: [
              'Sharp weapon (Knife, Dagger, Sword, Blade)',
              'Firearm (Pistol, Gun, Rifle)',
              'Heavy blunt object (Iron rod, Wooden bat, Brick)',
              'Physical violence (Bare hands, Choking, Stamping)',
              'Vehicle hit / Other tool',
            ],
          },
          {
            id: 'attacker_presence',
            question: 'Is the attacker or violent situation still active right now?',
            options: [
              'Attacker fled the scene after the attack',
              'Attacker is still present / active armed threat at the scene right now',
            ],
          },
        ],
      };
    }

    // 2. Ragging / College & Student Harassment / Hostel abuse / Senior intimidation
    if (
      lower.includes('ragging') ||
      lower.includes('ragged') ||
      lower.includes('senior') ||
      lower.includes('junior') ||
      lower.includes('college') ||
      lower.includes('hostel') ||
      lower.includes('campus') ||
      lower.includes('university') ||
      lower.includes('dormitory') ||
      lower.includes('student') ||
      lower.includes('dance') ||
      lower.includes('cctv') ||
      lower.includes('forcing me') ||
      lower.includes('forced me') ||
      (lower.includes('forcing') && (lower.includes('wrong') || lower.includes('bad') || lower.includes('things') || lower.includes('wish'))) ||
      lower.includes('bully')
    ) {
      return {
        questions: [
          {
            id: 'ragging_nature',
            question: 'What specific pressure or act are seniors/students forcing upon you?',
            options: [
              'Humiliating / degrading tasks (e.g., forced dancing, stripping, performing abusive acts against your will)',
              'Physical abuse (slapping, physical beating, restriction of movement in hostel room)',
              'Verbal intimidation, vulgar language, or psychological mental harassment',
              'Extortion of money, food, or forced personal servitude by seniors',
              'Capturing or circulating non-consensual photos/videos or online student bullying',
            ],
          },
          {
            id: 'ragging_location',
            question: 'Where did or does this incident occur?',
            options: [
              'Hostel room / Corridors / Mess / Campus premises',
              'College campus / Classrooms / Canteen grounds',
              'Outside campus / Private rented student room',
              'Online student social media / WhatsApp groups',
            ],
          },
          {
            id: 'ragging_threat',
            question: 'Is there an immediate physical beating or danger to your bodily safety right now?',
            options: [
              'No active physical assault right now, but ongoing harassment and intimidation',
              'Yes, active physical violence / armed threat / emergency danger at this moment',
            ],
          },
        ],
      };
    }

    // 3. Kidnapping / Abduction
    if (lower.includes('kidnap') || lower.includes('abduct') || lower.includes('hostage') || lower.includes('ransom')) {
      return {
        questions: [
          {
            id: 'kidnap_nature',
            question: 'Was the individual taken away by force against their will?',
            options: [
              'Yes, forcibly pulled into vehicle / abducted by suspects',
              'The person is untraceable / missing without known abduction',
            ],
          },
          {
            id: 'kidnap_timing',
            question: 'Is the kidnapping actively happening right now?',
            options: [
              'Happening right now / just occurred within minutes',
              'Occurred earlier / hours or days ago',
            ],
          },
        ],
      };
    }

    // 3. Robbery / Snatching / Theft / Burglary
    if (
      lower.includes('stole') ||
      lower.includes('steal') ||
      lower.includes('theft') ||
      lower.includes('rob') ||
      lower.includes('snatch') ||
      lower.includes('broken') ||
      lower.includes('burglary') ||
      lower.includes('loot')
    ) {
      return {
        questions: [
          {
            id: 'theft_method',
            question: 'How was the property or item taken?',
            options: [
              'Suspect broke into locked house/flat/shop (Burglary)',
              'Snatched or picked in a public street/transport (Theft/Snatching)',
              'Robbed using weapons like guns or knives (Armed Robbery)',
              'Lost or misplaced electronic device (Phone/Laptop)',
            ],
          },
          {
            id: 'item_type',
            question: 'What specific property was taken?',
            options: [
              'Mobile phone / Laptop / Tablet device',
              'Cash, Wallet, Gold / Jewelry',
              'Vehicle (Motorcycle, Scooter, Car)',
              'Household / Commercial goods',
            ],
          },
        ],
      };
    }

    // 4. Financial Fraud / Online Scam / Cybercrime
    if (
      lower.includes('bank') ||
      lower.includes('fraud') ||
      lower.includes('money') ||
      lower.includes('otp') ||
      lower.includes('upi') ||
      lower.includes('scam') ||
      lower.includes('hacked') ||
      lower.includes('cyber') ||
      lower.includes('account')
    ) {
      return {
        questions: [
          {
            id: 'fraud_type',
            question: 'What type of digital or financial fraud occurred?',
            options: [
              'Unauthorized online UPI / Card / Net banking deduction',
              'Deceived by fake caller / Fake investment or job scheme',
              'Social media / Email account hacked or password changed',
              'In-person business cheating / Forged cheque or contract',
            ],
          },
          {
            id: 'financial_loss',
            question: 'Did unauthorized financial loss take place from your account?',
            options: [
              'Yes, money was debited from bank / wallet',
              'No money lost, but unauthorized access or fake profile created',
            ],
          },
        ],
      };
    }

    // 5. Harassment / Threats / Domestic Violence
    if (
      lower.includes('threat') ||
      lower.includes('harass') ||
      lower.includes('abuse') ||
      lower.includes('blackmail') ||
      lower.includes('wife') ||
      lower.includes('husband') ||
      lower.includes('domestic') ||
      lower.includes('stalk')
    ) {
      return {
        questions: [
          {
            id: 'relation_nature',
            question: 'Who is the perpetrator and where is this taking place?',
            options: [
              'Spouse / In-laws / Family member at home (Domestic)',
              'Online / Social media / Phone messaging',
              'Known / Unknown person in person',
            ],
          },
          {
            id: 'threat_severity',
            question: 'What is the immediate nature of the threat?',
            options: [
              'Active immediate physical threat to life right now',
              'Blackmail demanding money or favors (Extortion)',
              'Verbal intimidation / Defamation / Obscene messages',
            ],
          },
        ],
      };
    }

    // Default general clarifying questions for unclear or short statements
    return {
      questions: [
        {
          id: 'incident_type',
          question: 'What is the primary nature of the incident you are reporting?',
          options: [
            'College / hostel / student harassment or ragging by seniors or peers',
            'Physical violence, injury, or loss of human life',
            'Cybercrime, online fraud, or banking loss',
            'Stolen property, theft, or house break-in',
            'Personal threats, harassment, or domestic dispute',
            'Property damage, vandalism, or missing person',
          ],
        },
        {
          id: 'emergency_status',
          question: 'Is there an ongoing active threat or emergency medical danger right now?',
          options: [
            'No, incident has already occurred and attacker is not present',
            'Yes, active violent threat or medical emergency right now',
          ],
        },
      ],
    };
  };

  // Check if case is still confusing / ambiguous after first round of answers
  const isStillConfusing = (
    origStatement: string,
    qa: Record<string, string>,
    round: number
  ): boolean => {
    if (round >= 2) return false;

    const combined = `${origStatement} ${Object.values(qa).join(' ')}`.toLowerCase();

    // 1. Clear Homicide signal
    if (combined.includes('kill') || combined.includes('murder') || combined.includes('dead') || combined.includes('homicide')) {
      return false;
    }
    // 2. Clear Ragging / Campus Harassment signal
    if (
      combined.includes('ragging') ||
      combined.includes('ragged') ||
      combined.includes('senior') ||
      combined.includes('junior') ||
      combined.includes('college') ||
      combined.includes('hostel') ||
      combined.includes('campus') ||
      combined.includes('university') ||
      combined.includes('dormitory') ||
      combined.includes('dance') ||
      combined.includes('cctv') ||
      combined.includes('without my wish') ||
      (combined.includes('student') && (combined.includes('forcing') || combined.includes('force') || combined.includes('wrong') || combined.includes('bad'))) ||
      qa['ragging_nature'] !== undefined ||
      qa['incident_type']?.toLowerCase().includes('ragging') ||
      qa['incident_type']?.toLowerCase().includes('college')
    ) {
      return false;
    }
    // 3. Clear Robbery / Armed / Kidnap
    if (combined.includes('gunpoint') || combined.includes('armed robbery') || combined.includes('kidnap') || combined.includes('abduct') || combined.includes('hostage')) {
      return false;
    }
    // 4. Clear Burglary / Theft / Device
    if (combined.includes('broke into') || combined.includes('burglary') || combined.includes('broken lock') || combined.includes('snatch') || combined.includes('pickpocket') || (combined.includes('phone') && (combined.includes('stolen') || combined.includes('lost')))) {
      return false;
    }
    // 5. Clear Financial Fraud / Cyber
    if (
      (combined.includes('bank') && (combined.includes('money') || combined.includes('debit') || combined.includes('transfer'))) ||
      combined.includes('otp') ||
      combined.includes('upi') ||
      combined.includes('phishing') ||
      combined.includes('hacked') ||
      combined.includes('ransomware')
    ) {
      return false;
    }
    // 6. Clear Domestic
    if (combined.includes('spouse') || combined.includes('husband') || combined.includes('wife') || combined.includes('in-laws') || combined.includes('dowry') || combined.includes('domestic violence')) {
      return false;
    }
    // 7. Clear Physical assault
    if (combined.includes('slap') || combined.includes('punched') || combined.includes('beaten') || combined.includes('fracture') || combined.includes('bleeding')) {
      return false;
    }

    // If none of these clear signals matched, the case is still ambiguous/confusing!
    return true;
  };

  // Generate deeper follow-up questions when still ambiguous
  const generateFollowupQuestions = (): QuestionDef[] => {
    return [
      {
        id: 'followup_environment',
        question: 'Which specific environment or relationship does this incident involve?',
        options: [
          'College / Hostel / Educational institution involving seniors or fellow students (Ragging / Student Harassment)',
          'Personal confrontation, assault, or altercation in a public/private place',
          'Online internet / Social media / Phone messaging or digital platforms',
          'Bank account / Online payment / Investment scam or monetary fraud',
          'Home / Residential premises / Domestic family relation',
          'Property, vehicle, or personal device theft / damage',
        ],
      },
      {
        id: 'followup_nature_of_offense',
        question: 'What was the specific violation or harm you experienced?',
        options: [
          'Forced humiliating acts, obedience without consent, or mental harassment by seniors/others',
          'Direct bodily injury, slapping, physical beating, or assault',
          'Loss of money from bank account or unauthorized online transaction',
          'Theft or loss of mobile phone, vehicle, or personal belongings',
          'Verbal intimidation, threats of harm, or blackmail',
          'Damage or vandalism to property/vehicle',
        ],
      },
    ];
  };

  // Evaluate the statement + answers to determine the exact Case Category
  const evaluateCategory = (
    origStatement: string,
    qa: Record<string, string>,
    passedQaList?: { question: string; answer: string }[]
  ): AnalysisResult => {
    const combined = `${origStatement} ${Object.values(qa).join(' ')}`.toLowerCase();
    const finalQaSummary = passedQaList && passedQaList.length > 0
      ? passedQaList
      : Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        }));

    // 1. Check for Murder (Homicide)
    // If victim died or statement mentions killing/murder + person died
    const isDeath =
      qa['death_status']?.includes('died') ||
      qa['death_status']?.includes('succumbed') ||
      combined.includes('died') ||
      combined.includes('dead') ||
      combined.includes('kill') ||
      combined.includes('murder');

    const weapon = qa['weapon_used'] || '';

    if (isDeath && (combined.includes('kill') || combined.includes('person') || combined.includes('knife') || combined.includes('gun') || combined.includes('murder') || combined.includes('weapon') || combined.includes('attack'))) {
      return {
        category: '[Emergency] Murder',
        isEmergency: true,
        confidence: 99,
        ipcSection: 'Section 302 IPC',
        bnsSection: 'Section 103 Bharatiya Nyaya Sanhita (BNS)',
        explanation: `Based on your statement that an individual was killed / lost life ${weapon ? `using ${weapon}` : 'in a violent attack'}, this case is legally classified as Homicide / Murder. As this involves loss of human life and severe cognizable capital offense, field police and forensics must be dispatched immediately.`,
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 2. Active violent assault / Immediate threat to life
    if (
      qa['attacker_presence']?.includes('still present') ||
      qa['threat_severity']?.includes('Active immediate') ||
      qa['emergency_status']?.includes('active violent') ||
      combined.includes('right now') && (combined.includes('attack') || combined.includes('life'))
    ) {
      return {
        category: '[Emergency] Active violent assault',
        isEmergency: true,
        confidence: 96,
        ipcSection: 'Section 307 / 326 IPC',
        bnsSection: 'Section 109 / 118 BNS',
        explanation: 'The incident involves an active violent altercation or immediate armed danger occurring at the scene right now. Rapid emergency response units (Dial 112) are required.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 3. Armed Robbery
    if (
      qa['theft_method']?.includes('Armed Robbery') ||
      (combined.includes('weapon') && (combined.includes('rob') || combined.includes('loot'))) ||
      combined.includes('gunpoint')
    ) {
      return {
        category: '[Emergency] Armed robbery',
        isEmergency: true,
        confidence: 97,
        ipcSection: 'Section 392 / 397 IPC',
        bnsSection: 'Section 309 / 311 BNS',
        explanation: 'Forced robbery committed with deadly weapons poses immediate danger and is categorized under Armed Robbery (Emergency Dispatch).',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 4. Kidnapping in Progress
    if (
      qa['kidnap_nature']?.includes('forcibly pulled') ||
      (combined.includes('kidnap') && qa['kidnap_timing']?.includes('actively happening'))
    ) {
      return {
        category: '[Emergency] Kidnapping in progress',
        isEmergency: true,
        confidence: 98,
        ipcSection: 'Section 364 / 365 IPC',
        bnsSection: 'Section 138 / 140 BNS',
        explanation: 'Active abduction or kidnapping of a person against their will requires immediate highway intercepts and mobile patrol deployment.',
        statement: origStatement,
        qaSummary: finalQaSummary,
      };
    }

    // 5. Ragging / Campus & Student Harassment
    const isRagging =
      combined.includes('ragging') ||
      combined.includes('ragged') ||
      combined.includes('senior') ||
      combined.includes('seniors') ||
      combined.includes('junior') ||
      combined.includes('juniors') ||
      combined.includes('hostel') ||
      combined.includes('college') ||
      combined.includes('campus') ||
      combined.includes('university') ||
      combined.includes('dormitory') ||
      combined.includes('cctv') ||
      combined.includes('dance') ||
      combined.includes('without my wish') ||
      (combined.includes('student') && (combined.includes('forcing') || combined.includes('force') || combined.includes('bad') || combined.includes('wrong'))) ||
      qa['ragging_nature'] !== undefined ||
      qa['ragging_location'] !== undefined ||
      qa['incident_type']?.toLowerCase().includes('ragging') ||
      qa['incident_type']?.toLowerCase().includes('college') ||
      qa['followup_environment']?.toLowerCase().includes('ragging') ||
      qa['followup_environment']?.toLowerCase().includes('college') ||
      qa['followup_nature_of_offense']?.toLowerCase().includes('forced humiliating');

    if (isRagging) {
      const isEmergencyThreat =
        qa['ragging_threat']?.includes('Yes, active physical') ||
        combined.includes('active beating right now') ||
        combined.includes('bleeding heavily');

      if (isEmergencyThreat) {
        return {
          category: '[Emergency] Active violent assault',
          isEmergency: true,
          confidence: 98,
          ipcSection: 'Section 307 / 326 IPC & Anti-Ragging Act',
          bnsSection: 'Section 109 / 118 BNS',
          explanation: 'Active physical violence, battery, or bodily harm in an educational hostel or campus setting requires immediate emergency police intervention (Dial 112).',
          statement: origStatement,
          qaSummary: finalQaSummary,
        };
      }

      return {
        category: 'Ragging / Campus harassment',
        isEmergency: false,
        confidence: 99,
        ipcSection: 'Section 341, 354, 506, 323 IPC & UGC Anti-Ragging Regulations',
        bnsSection: 'Section 126, 351, 115 BNS & State Prohibition of Ragging Act',
        explanation: 'Subjecting a student or junior to humiliating acts, forced tasks against their will (such as forced dancing, abusive commands, hostel harassment, or psychological pressure) constitutes the cognizable offense of Ragging under Supreme Court directives and UGC Regulations. Eligible for immediate Online FIR registration.',
        statement: origStatement,
        qaSummary: finalQaSummary,
      };
    }

    // 6. Burglary (House/shop break-in)
    if (
      qa['theft_method']?.includes('broke into') ||
      combined.includes('break') ||
      combined.includes('broken lock') ||
      combined.includes('burglary')
    ) {
      return {
        category: 'Burglary',
        isEmergency: false,
        confidence: 95,
        ipcSection: 'Section 457 / 380 IPC',
        bnsSection: 'Section 305 / 331 BNS',
        explanation: 'Trespassing into locked premises, breaking locks or windows, and stealing property is categorized as Burglary (Lurking house-trespass / theft). Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 6. Lost / Stolen Devices
    if (
      qa['theft_method']?.includes('Lost or misplaced') ||
      qa['item_type']?.includes('Mobile phone') ||
      (combined.includes('phone') && (combined.includes('lost') || combined.includes('stolen') || combined.includes('snatch'))) ||
      combined.includes('imei')
    ) {
      return {
        category: 'Lost/stolen devices',
        isEmergency: false,
        confidence: 96,
        ipcSection: 'Section 379 IPC',
        bnsSection: 'Section 303 BNS',
        explanation: 'Loss or theft of electronic communication equipment (Smartphones, Laptops, Tablets) falls under Lost/stolen devices with CEIR / IMEI tracking registry. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 7. General Theft
    if (
      qa['theft_method']?.includes('Snatched') ||
      qa['item_type']?.includes('Vehicle') ||
      qa['item_type']?.includes('Cash') ||
      combined.includes('theft') ||
      combined.includes('stole') ||
      combined.includes('snatch')
    ) {
      return {
        category: 'Theft',
        isEmergency: false,
        confidence: 94,
        ipcSection: 'Section 379 IPC',
        bnsSection: 'Section 303 BNS',
        explanation: 'Taking movable property without consent in a public place or transit without violent break-in constitutes Theft. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 8. Online Fraud / Cybercrime
    if (
      qa['fraud_type']?.includes('online UPI') ||
      qa['fraud_type']?.includes('fake caller') ||
      combined.includes('otp') ||
      combined.includes('upi') ||
      combined.includes('link') ||
      combined.includes('phishing') ||
      combined.includes('online fraud')
    ) {
      return {
        category: 'Online fraud',
        isEmergency: false,
        confidence: 96,
        ipcSection: 'Section 420 IPC & Section 66D IT Act',
        bnsSection: 'Section 318 BNS',
        explanation: 'Unauthorized online financial diversion via deceptive links, OTP fraud, phishing, or spoofed portals is classified under Online Fraud. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 9. Hacking / Cybercrime
    if (qa['fraud_type']?.includes('hacked') || combined.includes('hack') || combined.includes('ransomware') || combined.includes('malware')) {
      return {
        category: 'Hacking',
        isEmergency: false,
        confidence: 93,
        ipcSection: 'Section 43 / 66 Information Technology Act',
        bnsSection: 'IT Act 2000',
        explanation: 'Unauthorized electronic intrusion into personal accounts, servers, databases, or digital services is categorized as Hacking. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 10. Domestic Violence
    if (
      qa['relation_nature']?.includes('Spouse') ||
      combined.includes('domestic') ||
      combined.includes('in-laws') ||
      combined.includes('husband') ||
      combined.includes('dowry')
    ) {
      return {
        category: 'Domestic violence',
        isEmergency: false,
        confidence: 95,
        ipcSection: 'Section 498A IPC & Protection of Women from Domestic Violence Act',
        bnsSection: 'Section 85 BNS',
        explanation: 'Physical, verbal, or emotional abuse occurring within a domestic relationship falls under Domestic Violence legislation. Eligible for Online FIR filing.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 11. Extortion / Blackmail
    if (
      qa['threat_severity']?.includes('Extortion') ||
      combined.includes('blackmail') ||
      combined.includes('extort') ||
      combined.includes('ransom')
    ) {
      return {
        category: 'Extortion',
        isEmergency: false,
        confidence: 94,
        ipcSection: 'Section 384 IPC',
        bnsSection: 'Section 308 BNS',
        explanation: 'Intentionally putting any person in fear of injury or reputation damage to demand money or property constitutes Extortion. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 12. Missing Person
    if (
      qa['kidnap_nature']?.includes('untraceable') ||
      combined.includes('missing') ||
      combined.includes('lost person') ||
      combined.includes('disappeared')
    ) {
      return {
        category: 'Missing person',
        isEmergency: false,
        confidence: 95,
        ipcSection: 'Section 154 CrPC Missing Persons Registry',
        bnsSection: 'BNSS 173 Missing Persons Registry',
        explanation: 'A person whose whereabouts are unknown without verified kidnapping/ransom demand is registered under Missing Person inquiry.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 13. Physical Assault (Non-emergency)
    if (
      qa['death_status']?.includes('survived') ||
      combined.includes('assault') ||
      combined.includes('beaten') ||
      combined.includes('slap') ||
      combined.includes('fight')
    ) {
      return {
        category: 'Physical assault',
        isEmergency: false,
        confidence: 93,
        ipcSection: 'Section 323 / 324 IPC',
        bnsSection: 'Section 115 / 117 BNS',
        explanation: 'Voluntarily causing hurt or injury in a past incident without ongoing life threat is categorized as Physical Assault. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 14. Threats / Intimidation
    if (
      qa['threat_severity']?.includes('Verbal intimidation') ||
      combined.includes('threat') ||
      combined.includes('warn')
    ) {
      return {
        category: 'Threats',
        isEmergency: false,
        confidence: 92,
        ipcSection: 'Section 506 IPC',
        bnsSection: 'Section 351 BNS',
        explanation: 'Criminal intimidation through words, messages, or gestures without active physical standoff is classified under Threats.',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // 15. Property Damage
    if (combined.includes('damage') || combined.includes('vandal') || combined.includes('destroy') || combined.includes('car window')) {
      return {
        category: 'Property damage',
        isEmergency: false,
        confidence: 91,
        ipcSection: 'Section 427 IPC (Mischief)',
        bnsSection: 'Section 324 BNS',
        explanation: 'Intentionally damaging or destroying private or public movable/immovable property is categorized as Property Damage (Mischief).',
        statement: origStatement,
        qaSummary: Object.entries(qa).map(([k, v]) => ({
          question: questions.find((q) => q.id === k)?.question || k,
          answer: v,
        })),
      };
    }

    // Intelligent context fallback — NEVER blindly guess "Online fraud"
    if (combined.includes('college') || combined.includes('student') || combined.includes('senior') || combined.includes('hostel') || combined.includes('dance') || combined.includes('ragging')) {
      return {
        category: 'Ragging / Campus harassment',
        isEmergency: false,
        confidence: 97,
        ipcSection: 'Section 341 / 506 IPC & UGC Anti-Ragging Regulations',
        bnsSection: 'Section 126 / 351 BNS',
        explanation: 'Harassment, forced acts, or intimidation directed at students within college/hostel settings falls under the legal classification of Ragging. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: finalQaSummary,
      };
    }

    if (combined.includes('bank') || combined.includes('money') || combined.includes('fraud') || combined.includes('cheated') || combined.includes('financial') || combined.includes('scam')) {
      return {
        category: 'Online fraud',
        isEmergency: false,
        confidence: 90,
        ipcSection: 'Section 420 IPC',
        bnsSection: 'Section 318 BNS',
        explanation: 'Unauthorized online financial diversion or cheating is classified under Online Fraud. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: finalQaSummary,
      };
    }

    if (combined.includes('hit') || combined.includes('beat') || combined.includes('pain') || combined.includes('attack') || combined.includes('slap')) {
      return {
        category: 'Physical assault',
        isEmergency: false,
        confidence: 92,
        ipcSection: 'Section 323 IPC',
        bnsSection: 'Section 115 BNS',
        explanation: 'Causing hurt or physical violence to a person constitutes Physical Assault. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: finalQaSummary,
      };
    }

    if (combined.includes('online') || combined.includes('internet') || combined.includes('message') || combined.includes('social')) {
      return {
        category: 'Online harassment',
        isEmergency: false,
        confidence: 90,
        ipcSection: 'Section 354D / 509 IPC & Section 67 IT Act',
        bnsSection: 'Section 78 BNS',
        explanation: 'Digital harassment or unwanted messaging is classified under Online Harassment. Eligible for Online FIR.',
        statement: origStatement,
        qaSummary: finalQaSummary,
      };
    }

    // Default safe fallback is Threats (Criminal Intimidation)
    return {
      category: 'Threats',
      isEmergency: false,
      confidence: 88,
      ipcSection: 'Section 506 IPC',
      bnsSection: 'Section 351 BNS',
      explanation: 'Based on the reported incident facts and intimidation/coercion described, the case is classified under Criminal Intimidation & Threats. Eligible for Online FIR processing.',
      statement: origStatement,
      qaSummary: finalQaSummary,
    };
  };

  // Step 1: Handle initial analysis click
  const handleAnalyzeStatement = () => {
    if (!statement.trim() || statement.trim().length < 5) {
      return;
    }

    setIsAnalyzing(true);

    setTimeout(() => {
      setIsAnalyzing(false);
      const { questions: generatedQuestions } = generateQuestionsForStatement(statement);
      setQuestions(generatedQuestions);
      setAnswers({});
      setCustomAnswerInput({});
      setRecordedQa([]);
      setClarificationRound(1);
      setStep('clarifying');
    }, 600);
  };

  // Handle selecting an option for a question
  const handleSelectOption = (questionId: string, option: string) => {
    setAnswers((prev) => ({
      ...prev,
      [questionId]: option,
    }));
  };

  // Step 2: Handle submitting clarification answers
  const handleSubmitClarifications = () => {
    // Incorporate any typed custom answers if chosen option is empty
    const finalAnswers: Record<string, string> = { ...answers };
    questions.forEach((q) => {
      if (!finalAnswers[q.id] && customAnswerInput[q.id]?.trim()) {
        finalAnswers[q.id] = customAnswerInput[q.id].trim();
      }
    });

    // Check if the AI is still confused/ambiguous
    if (clarificationRound === 1 && isStillConfusing(statement, finalAnswers, 1)) {
      setIsAnalyzing(true);
      setTimeout(() => {
        setIsAnalyzing(false);
        // Save current round Q&A
        const currentQaList = questions.map((q) => ({
          question: q.question,
          answer: finalAnswers[q.id] || 'Not specified',
        }));
        setRecordedQa(currentQaList);

        // Generate follow-up questions to resolve the ambiguity
        const followupQuestions = generateFollowupQuestions();
        setQuestions(followupQuestions);
        setAnswers({});
        setCustomAnswerInput({});
        setClarificationRound(2);
      }, 600);
      return;
    }

    setIsAnalyzing(true);
    setTimeout(() => {
      setIsAnalyzing(false);
      // Combine all recorded QA with current answers
      const currentQaList = questions.map((q) => ({
        question: q.question,
        answer: finalAnswers[q.id] || 'Not specified',
      }));
      const fullQaList = [...recordedQa, ...currentQaList];

      const allAnswersMap: Record<string, string> = { ...finalAnswers };
      recordedQa.forEach((item, idx) => {
        allAnswersMap[`prev_round_q_${idx}`] = `${item.question}: ${item.answer}`;
      });

      const result = evaluateCategory(statement, allAnswersMap, fullQaList);
      setAnalysisResult(result);
      setStep('result');
    }, 600);
  };

  // Step 3: Handle user confirming the AI identified category
  const handleConfirmCategory = () => {
    if (!analysisResult) return;

    // Compose a clear AI summary for audit and pre-filling description
    const qaDetails = analysisResult.qaSummary
      .map((item) => `• ${item.question}: ${item.answer}`)
      .join('\n');

    const summaryText = `[AI Classified Case Category: ${analysisResult.category}]\nIncident Statement: "${analysisResult.statement}"\n\nAI Clarifications:\n${qaDetails}\n\nLegal Assessment: ${analysisResult.explanation}`;

    onConfirmCategory(analysisResult.category, statement, summaryText);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/80 backdrop-blur-md overflow-y-auto">
      <div
        className="w-full max-w-2xl my-auto rounded-2xl border border-white/20 bg-[#0b1329] text-white shadow-2xl overflow-hidden flex flex-col transition-all"
        style={{
          boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75), 0 25px 50px -12px rgba(0, 0, 0, 0.9)',
        }}
      >
        {/* Modal Top Header */}
        <div className="px-5 py-4 bg-slate-900/90 border-b border-white/15 flex items-center justify-between">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white flex items-center justify-center shadow-md">
              <Bot className="w-5 h-5 text-white" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-[10px] font-black uppercase tracking-wider text-cyan-400 bg-cyan-950/60 px-2 py-0.5 rounded-full border border-cyan-500/30">
                  Judicial AI Assistant
                </span>
                <span className="text-[10px] text-slate-400 font-semibold">• Case Categorization</span>
              </div>
              <h3 className="text-sm sm:text-base font-black uppercase tracking-wider text-white">
                Case Category Identification & Fact Analysis
              </h3>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-5 sm:p-6 space-y-5 max-h-[78vh] overflow-y-auto">
          {/* STEP 1: STATEMENT INPUT */}
          {step === 'input' && (
            <div className="space-y-4">
              <div
                className="p-3.5 rounded-xl border border-cyan-400/30 bg-blue-950/40 backdrop-blur-md text-slate-200 text-xs flex items-start space-x-3 shadow-inner"
                style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
              >
                <Sparkles className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5 animate-pulse" />
                <p className="leading-relaxed">
                  Don't know which legal category your case belongs to? Describe what happened in your own words.
                  Our AI legal assistant will analyze the incident, ask necessary clarifying questions, and identify the exact category for you.
                </p>
              </div>

              <div className="space-y-2">
                <label className="block text-xs font-extrabold uppercase tracking-wider text-slate-200">
                  Describe what happened (Incident Statement) *
                </label>
                <textarea
                  rows={4}
                  value={statement}
                  onChange={(e) => setStatement(e.target.value)}
                  placeholder="e.g. A saw a person who kill the another person Infront of me / Someone sent a fake link and stole money from my bank account / My mobile phone was snatched on the street..."
                  className="w-full p-3.5 rounded-xl text-sm font-medium focus:outline-none transition-all border border-white/20 bg-slate-900/70 hover:bg-slate-900/90 text-white placeholder:text-slate-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-500/25 shadow-inner"
                  style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
                />
              </div>

              {/* Sample Statement Chips */}
              <div className="space-y-1.5 pt-1">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
                  Quick Examples (Click to test):
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {sampleStatements.map((sample, idx) => (
                    <button
                      key={idx}
                      type="button"
                      onClick={() => setStatement(sample)}
                      className="text-left text-[11px] px-2.5 py-1.5 rounded-lg border border-white/10 bg-slate-900/50 hover:bg-white/10 text-slate-300 hover:text-cyan-300 transition-colors cursor-pointer"
                    >
                      "{sample}"
                    </button>
                  ))}
                </div>
              </div>

              <div className="pt-2 flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2 rounded-xl text-xs font-bold border border-white/20 bg-white/10 hover:bg-white/20 text-white transition-all cursor-pointer"
                >
                  Cancel
                </button>

                <button
                  type="button"
                  onClick={handleAnalyzeStatement}
                  disabled={!statement.trim() || isAnalyzing}
                  className={`px-5 py-2.5 rounded-xl text-xs sm:text-sm font-black uppercase tracking-wider transition-all flex items-center space-x-2 cursor-pointer shadow-lg ${
                    statement.trim() && !isAnalyzing
                      ? 'bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white border border-cyan-400/40 active:scale-95'
                      : 'bg-slate-800 text-slate-500 border border-white/10 cursor-not-allowed'
                  }`}
                  style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
                >
                  {isAnalyzing ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin text-cyan-300" />
                      <span>Analyzing Statement...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 text-cyan-300" />
                      <span>Analyze Incident with AI</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* STEP 2: AI CLARIFYING QUESTIONS */}
          {step === 'clarifying' && (
            <div className="space-y-5">
              {/* Display original statement */}
              <div className="p-3 rounded-xl border border-white/15 bg-slate-900/60 text-xs">
                <span className="font-bold text-slate-400 uppercase tracking-wider block mb-1">
                  Your Incident Statement:
                </span>
                <p className="text-white font-medium italic">"{statement}"</p>
              </div>

              {/* AI Notice Banner */}
              {clarificationRound === 2 ? (
                <div
                  className="p-3.5 rounded-xl border border-amber-400/40 bg-amber-950/40 text-xs text-amber-200 flex items-start space-x-2.5 shadow-inner"
                  style={{ boxShadow: '0 0 0 0.75px rgba(251, 191, 36, 0.75)' }}
                >
                  <HelpCircle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5 animate-pulse" />
                  <p className="leading-relaxed">
                    <strong>Clarification Follow-Up:</strong> To avoid any confusion between distinct case types (e.g. Campus Ragging vs. Online matters), please answer these targeted questions to accurately isolate the legal category:
                  </p>
                </div>
              ) : (
                <div
                  className="p-3.5 rounded-xl border border-cyan-400/30 bg-cyan-950/40 text-xs text-cyan-200 flex items-start space-x-2.5 shadow-inner"
                  style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
                >
                  <HelpCircle className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                  <p className="leading-relaxed">
                    To determine the exact legal Case Category with high accuracy, please answer the following clarifying questions based on your statement:
                  </p>
                </div>
              )}

              {/* Clarifying Questions List */}
              <div className="space-y-4">
                {questions.map((q, qIndex) => {
                  const currentAnswer = answers[q.id];
                  return (
                    <div
                      key={q.id}
                      className="p-4 rounded-xl border border-white/15 bg-slate-900/70 space-y-2.5"
                      style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
                    >
                      <label className="block text-xs sm:text-sm font-black text-cyan-300">
                        {qIndex + 1}. {q.question} *
                      </label>

                      {/* Option Pills */}
                      <div className="grid grid-cols-1 gap-2 pt-1">
                        {q.options.map((opt, optIndex) => {
                          const isSelected = currentAnswer === opt;
                          return (
                            <button
                              key={optIndex}
                              type="button"
                              onClick={() => handleSelectOption(q.id, opt)}
                              className={`w-full text-left p-2.5 rounded-xl text-xs font-semibold transition-all flex items-center justify-between cursor-pointer border ${
                                isSelected
                                  ? 'bg-blue-600/30 border-cyan-400 text-white shadow-md'
                                  : 'bg-slate-950/60 border-white/10 text-slate-300 hover:bg-white/10 hover:text-white'
                              }`}
                              style={
                                isSelected
                                  ? { boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }
                                  : undefined
                              }
                            >
                              <span>{opt}</span>
                              {isSelected && <Check className="w-4 h-4 text-cyan-400 shrink-0 ml-2" />}
                            </button>
                          );
                        })}
                      </div>

                      {/* Or write custom answer */}
                      <div className="pt-1">
                        <input
                          type="text"
                          value={customAnswerInput[q.id] || ''}
                          onChange={(e) => {
                            const val = e.target.value;
                            setCustomAnswerInput((prev) => ({ ...prev, [q.id]: val }));
                            if (val) {
                              setAnswers((prev) => ({ ...prev, [q.id]: val }));
                            }
                          }}
                          placeholder="Or type specific details here..."
                          className="w-full px-3 py-2 rounded-lg text-xs border border-white/15 bg-slate-950/60 text-white placeholder:text-slate-500 focus:outline-none focus:border-cyan-400"
                        />
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Navigation buttons */}
              <div className="pt-2 flex items-center justify-between">
                <button
                  type="button"
                  onClick={() => {
                    if (clarificationRound === 2) {
                      setClarificationRound(1);
                      const { questions: initialQ } = generateQuestionsForStatement(statement);
                      setQuestions(initialQ);
                      setAnswers({});
                      setCustomAnswerInput({});
                    } else {
                      setStep('input');
                    }
                  }}
                  className="px-4 py-2 rounded-xl text-xs font-bold border border-white/20 bg-white/10 hover:bg-white/20 text-white transition-all cursor-pointer"
                >
                  {clarificationRound === 2 ? 'Back to Initial Questions' : 'Back to Statement'}
                </button>

                <button
                  type="button"
                  onClick={handleSubmitClarifications}
                  disabled={isAnalyzing}
                  className="px-5 py-2.5 rounded-xl text-xs sm:text-sm font-black uppercase tracking-wider transition-all flex items-center space-x-2 cursor-pointer shadow-lg bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white border border-cyan-400/40 active:scale-95"
                  style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
                >
                  {isAnalyzing ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin text-cyan-300" />
                      <span>{clarificationRound === 1 ? 'Analyzing Details...' : 'Determining Category...'}</span>
                    </>
                  ) : (
                    <>
                      <span>{clarificationRound === 1 ? 'Determine Category' : 'Finalize & Confirm Category'}</span>
                      <ArrowRight className="w-4 h-4 text-cyan-300" />
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* STEP 3: AI RESULT & USER CONFIRMATION */}
          {step === 'result' && analysisResult && (
            <div className="space-y-5">
              {/* Category Result Box */}
              <div
                className={`p-5 rounded-2xl border ${
                  analysisResult.isEmergency
                    ? 'border-rose-500/50 bg-rose-950/30'
                    : 'border-emerald-500/50 bg-emerald-950/30'
                } backdrop-blur-md text-white space-y-4`}
                style={{
                  boxShadow: analysisResult.isEmergency
                    ? '0 0 0 0.75px rgba(244, 63, 94, 0.75)'
                    : '0 0 0 0.75px rgba(52, 211, 153, 0.75)',
                }}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="space-y-1">
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">
                      AI Identified Case Category
                    </span>
                    <h2
                      className={`text-lg sm:text-xl font-black uppercase tracking-wide ${
                        analysisResult.isEmergency ? 'text-rose-400' : 'text-emerald-400'
                      }`}
                    >
                      {analysisResult.category}
                    </h2>
                  </div>

                  <span
                    className={`px-3 py-1 rounded-full text-xs font-black uppercase tracking-wider shrink-0 border ${
                      analysisResult.isEmergency
                        ? 'bg-rose-500/20 text-rose-300 border-rose-500/40'
                        : 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                    }`}
                  >
                    {analysisResult.isEmergency ? '🚨 Critical Emergency' : '✓ Online FIR Eligible'}
                  </span>
                </div>

                {/* Legal Sections & Confidence */}
                <div className="flex flex-wrap gap-2 text-xs">
                  <span className="px-2.5 py-1 rounded-lg bg-slate-900/80 border border-white/15 text-cyan-300 font-mono font-bold">
                    {analysisResult.ipcSection}
                  </span>
                  <span className="px-2.5 py-1 rounded-lg bg-slate-900/80 border border-white/15 text-cyan-300 font-mono font-bold">
                    {analysisResult.bnsSection}
                  </span>
                  <span className="px-2.5 py-1 rounded-lg bg-slate-900/80 border border-white/15 text-slate-300 font-bold">
                    Confidence: {analysisResult.confidence}%
                  </span>
                </div>

                {/* AI Legal Explanation */}
                <div className="p-3.5 rounded-xl bg-slate-900/80 border border-white/10 text-xs leading-relaxed text-slate-200">
                  <p className="font-semibold text-cyan-200 mb-1">Legal Analysis & Assessment:</p>
                  <p>{analysisResult.explanation}</p>
                </div>

                {/* Emergency Notice if Emergency */}
                {analysisResult.isEmergency && (
                  <div className="p-3 rounded-xl bg-rose-900/40 border border-rose-500/30 text-xs text-rose-200 flex items-start space-x-2">
                    <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5 animate-bounce" />
                    <p>
                      <strong>Important Notice:</strong> Because this category involves active life threats or capital offense, confirming this category will direct you to immediate emergency police dispatch (Dial 112 / 100) and further online form submission will be blocked.
                    </p>
                  </div>
                )}
              </div>

              {/* Q&A Summary */}
              <div className="p-4 rounded-xl border border-white/15 bg-slate-900/50 space-y-2 text-xs">
                <span className="font-extrabold uppercase tracking-wider text-slate-400 block">
                  Incident Statement & Clarification Summary
                </span>
                <p className="text-white font-medium">
                  <strong>Statement:</strong> "{analysisResult.statement}"
                </p>
                {analysisResult.qaSummary.map((item, i) => (
                  <div key={i} className="pl-3 border-l-2 border-cyan-500/40 text-slate-300">
                    <span className="font-bold text-cyan-300">{item.question}:</span> {item.answer}
                  </div>
                ))}
              </div>

              {/* Confirmation Question & Action Buttons */}
              <div
                className="p-4 sm:p-5 rounded-2xl border border-white/20 bg-slate-900/80 space-y-3"
                style={{ boxShadow: '0 0 0 0.75px rgba(56, 189, 248, 0.75)' }}
              >
                <div className="text-center space-y-1">
                  <h4 className="text-sm font-black uppercase tracking-wider text-white">
                    Confirm Case Category
                  </h4>
                  <p className="text-xs text-slate-300">
                    Is the category <span className="font-black text-cyan-300">"{analysisResult.category}"</span> identified by the AI correct for your case?
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
                  <button
                    type="button"
                    onClick={() => {
                      setStep('input');
                      setClarificationRound(1);
                      setRecordedQa([]);
                      setAnswers({});
                      setCustomAnswerInput({});
                    }}
                    className="w-full py-2.5 px-4 rounded-xl text-xs font-bold uppercase tracking-wider border border-white/20 bg-white/10 hover:bg-white/20 text-white transition-all cursor-pointer flex items-center justify-center space-x-1.5"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                    <span>No, Re-analyze / Edit</span>
                  </button>

                  <button
                    type="button"
                    onClick={handleConfirmCategory}
                    className={`w-full py-2.5 px-4 rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer flex items-center justify-center space-x-1.5 shadow-lg active:scale-95 ${
                      analysisResult.isEmergency
                        ? 'bg-gradient-to-r from-rose-600 to-red-600 hover:from-rose-500 hover:to-red-500 text-white border border-rose-400/40'
                        : 'bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white border border-emerald-400/40'
                    }`}
                    style={{
                      boxShadow: analysisResult.isEmergency
                        ? '0 0 0 0.75px rgba(244, 63, 94, 0.75)'
                        : '0 0 0 0.75px rgba(52, 211, 153, 0.75)',
                    }}
                  >
                    <CheckCircle2 className="w-4 h-4" />
                    <span>Yes, Confirm This Category</span>
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
