import json
import re

with open("/tmp/clean_missing.json") as f:
    clean_missing = json.load(f)

# Built-in comprehensive mappings for all clean missing strings from the application
NEW_TRANSLATIONS = {
  # Case & APB Lists
  'No Cases Allotted': 'कोई मामला आवंटित नहीं है',
  'No Matching Cases Found': 'कोई मेल खाता मामला नहीं मिला',
  'Try adjusting your completion status filter or search query.': 'कृपया अपना स्थिति फ़िल्टर या खोज क्वेरी समायोजित करें।',
  'Broadcast Ledger': 'प्रसारण बहीखाता (लेजर)',
  'Routine Coordination': 'सामान्य समन्वय',
  'High Urgency': 'उच्च तात्कालिकता',
  'Flash APB (Immediate Action)': 'फ्लैश एपीबी (त्वरित कार्रवाई)',
  'Submit Alert & Dispatch APB': 'अलर्ट सबमिट करें एवं एपीबी भेजें',
  'All States': 'सभी राज्य',
  'No Alerts Found': 'कोई अलर्ट नहीं मिला',
  'No APBs match your filter criteria.': 'आपकी फ़िल्टर शर्तों से मेल खाने वाला कोई एपीबी नहीं मिला।',
  'Print APB Dispatch Slip': 'एपीबी प्रेषण पर्ची प्रिंट करें',
  'e.g. Koramangala Police Station / Cyber Cell HQ': 'उदा. कोरामंगला पुलिस स्टेशन / साइबर सेल मुख्यालय',
  'e.g. CR-2026-8942': 'उदा. CR-2026-8942',
  'Write the exact description for what purpose you are contacting this police station (e.g. Suspect physical description, vehicle license number, last known location ping, request for CCTV backup, joint raid coordination, arrest warrant execution assistance)...': 'इस पुलिस स्टेशन से संपर्क करने का सटीक उद्देश्य लिखें (उदा. संदिग्ध का शारीरिक विवरण, वाहन संख्या, अंतिम ज्ञात स्थान, सीसीटीवी फुटेज बैकअप, संयुक्त छापेमारी समन्वय, गिरफ्तारी वारंट निष्पादन)...',
  'Search alerts, police station, or reference...': 'अलर्ट, पुलिस स्टेशन, या संदर्भ खोजें...',
  'Generate New CAPTCHA': 'नया कैप्चा बनाएं',
  'ENTER CAPTCHA CODE HERE': 'यहाँ कैप्चा कोड दर्ज करें',
  'Go to the website and watch the video': 'वेबसाइट पर जाएं और वीडियो देखें',
  'Alleged Offense:': 'कथित अपराध:',
  'Alleged Offense': 'कथित अपराध',
  'No suspects currently linked to this case record.': 'वर्तमान में इस केस रिकॉर्ड से कोई संदिग्ध जुड़ा नहीं है।',
  'PHOTO EXHIBIT': 'फोटो प्रदर्श (सबूत)',
  'Photo Title / File Name:': 'फोटो शीर्षक / फ़ाइल का नाम:',
  'Uploaded By:': 'अपलोडकर्ता:',
  'Upload Timestamp & Size:': 'अपलोड समय एवं आकार:',
  'Relevance / Description:': 'प्रासंगिकता / विवरण:',
  '📥 Download PDF / Save File': '📥 पीडीएफ डाउनलोड करें / फ़ाइल सहेजें',
  'Close Page': 'पेज बंद करें',
  'JUDICIAL INFORMATION SYSTEM • CASE DOSSIER': 'न्यायिक सूचना प्रणाली • केस दस्तावेज़ (डोज़ियर)',
  'State Cyber & Crime Branch • Official Investigation Record': 'राज्य साइबर एवं अपराध शाखा • आधिकारिक जांच रिकॉर्ड',
  'Case Title': 'केस का शीर्षक',
  'Crime Category & Status': 'अपराध श्रेणी एवं स्थिति',
  'Case Description & Overview': 'केस विवरण एवं अवलोकन',
  'Host Administrator': 'होस्ट व्यवस्थापक',
  'File / Record Title': 'फ़ाइल / रिकॉर्ड शीर्षक',
  'Size & Timestamp': 'आकार एवं समय',
  'Priority:': 'प्राथमिकता:',
  'Last Updated:': 'अंतिम अपडेट:',
  'Victim / Complainant': 'पीड़ित / शिकायतकर्ता',
  '🔒 Case Solved (Read-Only)': '🔒 केस हल हो चुका है (केवल पढ़ने योग्य)',
  'Add / Edit Suspects': 'संदिग्ध जोड़ें / संपादित करें',
  'All files are securely visible to assigned team members.': 'सभी फ़ाइलें आवंटित टीम के सदस्यों को सुरक्षित रूप से दिखाई देती हैं।',
  '🔒 Case Solved (Vault Locked)': '🔒 केस हल हो चुका है (वॉल्ट लॉक)',
  'Upload New Evidence / Photo': 'नया साक्ष्य / फोटो अपलोड करें',
  'Click or drop another file to replace': 'बदलने के लिए क्लिक करें या दूसरी फ़ाइल छोड़ें',
  'Document / File Title *': 'दस्तावेज़ / फ़ाइल का शीर्षक *',
  'File Category': 'फ़ाइल श्रेणी',
  'Document / Report': 'दस्तावेज़ / रिपोर्ट',
  'Image / Photograph': 'छवि / तस्वीर',
  'CCTV / Video Recording': 'सीसीटीवी / वीडियो रिकॉर्डिंग',
  'Audio / Wiretap': 'ऑडियो / वायरटैप',
  'Forensic Analysis': 'फोरेंसिक विश्लेषण',
  'Brief Description *': 'संक्षिप्त विवरण *',
  'Confirm Upload & Notify Team': 'अपलोड की पुष्टि करें एवं टीम को सूचित करें',
  'Notes / Comments:': 'टिप्पणियां / नोट्स:',
  'View Photo': 'फोटो देखें',
  'Confirm Delete': 'हटाने की पुष्टि करें',
  'Case Time-line': 'केस समयरेखा',
  'Progress Bar': 'प्रगति पट्टी',
  'Close Case': 'केस बंद करें',
  'CRIME MATRIX SYSTEM • OFFICIAL CASE DOSSIER': 'क्राइम मैट्रिक्स प्रणाली • आधिकारिक केस दस्तावेज़',
  'State Cyber & Crime Branch • Confidential Judicial Investigation Record': 'राज्य साइबर एवं अपराध शाखा • गोपनीय न्यायिक जांच रिकॉर्ड',
  'Full Case Description & Overview': 'पूर्ण केस विवरण एवं अवलोकन',
  'File / Record Name': 'फ़ाइल / रिकॉर्ड नाम',
  'Size & Upload Time': 'आकार एवं अपलोड समय',
  'PHOTO RECORD EXCLUSION': 'फोटो रिकॉर्ड विवरण',
  'Photo Name / Title:': 'फोटो नाम / शीर्षक:',
  'Uploaded By Officer:': 'अपलोडकर्ता अधिकारी:',
  'Timestamp & File Size:': 'समय एवं फ़ाइल आकार:',
  'Notes / Description:': 'टिप्पणी / विवरण:',
  'Close Case Details': 'केस विवरण बंद करें',
  'Selected preview': 'चयनित पूर्वावलोकन',
  'e.g. Ballistics_Analysis_Report.pdf': 'उदा. बैलिस्टिक_विश्लेषण_रिपोर्ट.pdf',
  'Describe relevance to case, key observations, or chain of custody notes...': 'केस से प्रासंगिकता, मुख्य टिप्पणियां या साक्ष्य संरक्षण नोट्स लिखें...',
  'Add notes, officer comments, or investigation remarks...': 'नोट्स, अधिकारी टिप्पणियां या जांच संबंधी बातें जोड़ें...',
  'Add or update notes and comments...': 'नोट्स और टिप्पणियां जोड़ें या अपडेट करें...',
  'Edit Evidence / Notes': 'साक्ष्य / नोट्स संपादित करें',
  'Confirm Deletion': 'हटाने की पुष्टि करें',
  'Delete / Remove Evidence File': 'साक्ष्य फ़ाइल हटाएं / निकालें',
  'Last 12 weeks': 'पिछले 12 सप्ताह',
  'Less': 'कम',
  'More': 'अधिक',
  '0 cases': '0 मामले',
  '1 case': '1 मामला',
  '2 cases': '2 मामले',
  '3 cases': '3 मामले',
  '4+ cases': '4+ मामले',
  'Victim:': 'पीड़ित:',
  'Witness:': 'गवाह:',
  "⚠️ No police officers assigned to this team yet. Click 'Assign Team' below.": "⚠️ अभी तक इस टीम में कोई पुलिस अधिकारी नियुक्त नहीं है। नीचे 'टीम नियुक्त करें' पर क्लिक करें।",
  'Delete Host': 'होस्ट हटाएं',
  'Crime Type *': 'अपराध का प्रकार *',
  'Cyber Attack': 'साइबर हमला',
  'Vehicle Theft': 'वाहन चोरी',
  'Priority Level': 'प्राथमिकता स्तर',
  'Case Title / FIR Name *': 'केस शीर्षक / एफआईआर नाम *',
  'Victim / Complainant Name *': 'पीड़ित / शिकायतकर्ता का नाम *',
  'Key Witness (Optional)': 'प्रमुख गवाह (वैकल्पिक)',
  'Assign Station Host Inspector *': 'थाना होस्ट इंस्पेक्टर नियुक्त करें *',
  'Case Description & FIR Summary *': 'केस विवरण एवं एफआईआर सारांश *',
  'Provide full crime narrative, FIR sections, incident background, and investigation directives...': 'पूर्ण अपराध विवरण, एफआईआर धाराएं, घटना की पृष्ठभूमि और जांच निर्देश प्रदान करें...',
  'Create & Register FIR Case': 'एफआईआर केस बनाएं एवं दर्ज करें',
  'FIR / Case Title': 'एफआईआर / केस का शीर्षक',
  'Full Crime Description': 'पूर्ण अपराध का विवरण',
  'Assigned Host:': 'आवंटित होस्ट:',
  'Hearing Date:': 'सुनवाई की तारीख:',
  'Next Hearing:': 'अगली सुनवाई:',
  'Assigned Officers:': 'आवंटित अधिकारी:',
  'Search within cases...': 'मामलों में खोजें...',
  'All Types': 'सभी प्रकार',
  'All Statuses': 'सभी स्थितियां',
  'Clearance:': 'मंजूरी:',
  'Dashboard:': 'डैशबोर्ड:',
  'Direct Police Station Approval': 'सीधी थाना स्वीकृति',
  'Victim Investigation Portal': 'पीड़ित जांच पोर्टल',
  'Victims Case Linking & Updates': 'पीड़ित का केस लिंकिंग एवं अपडेट',
  'Enter the registered Case ID to connect this victim to their case so they can view live case updates and court hearing schedules.': 'इस पीड़ित को उनके केस से जोड़ने के लिए पंजीकृत केस आईडी दर्ज करें ताकि वे लाइव केस अपडेट और अदालत सुनवाई कार्यक्रम देख सकें।',
  'Case ID *': 'केस आईडी *',
  'Enter or dial Case ID (e.g. CR-2026-8942)': 'केस आईडी दर्ज करें या डायल करें (उदा. CR-2026-8942)',
  'Dial Precinct Case:': 'थाना केस डायल करें:',
  'Case Record Verified': 'केस रिकॉर्ड सत्यापित',
  'Complainant / Victim:': 'शिकायतकर्ता / पीड़ित:',
  'Incident Location:': 'घटना स्थल:',
  'Next Court Hearing:': 'अगली अदालत सुनवाई:',
  'Station Investigation Team': 'थाना जांच दल',
  'Get limited access about the case updation': 'केस अपडेट की सीमित पहुंच प्राप्त करें',
  'Updates & Court Schedule Enabled': 'अपडेट एवं अदालत अनुसूची सक्षम',
  'Allow this victim to see case updates, investigation progress, and court update for Case': 'इस पीड़ित को केस के अपडेट, जांच प्रगति और अदालत अपडेट देखने की अनुमति दें',
  'Dial or enter a Case ID above to view the case details.': 'केस विवरण देखने के लिए ऊपर केस आईडी दर्ज या डायल करें।',
  'Once the Case ID is entered, the case details and limited access toggle will appear here.': 'केस आईडी दर्ज होने के बाद केस विवरण और सीमित पहुंच टॉगल यहाँ दिखाई देगा।',
  'Department / Police Branch *': 'विभाग / पुलिस शाखा *',
  'Specify Department *': 'विभाग निर्दिष्ट करें *',
  'Official Designation *': 'आधिकारिक पदनाम *',
  'Specify Designation *': 'पदनाम निर्दिष्ट करें *',
  'Badge ID / Service Number *': 'बैज आईडी / सेवा संख्या *',
  'Years of Service / Experience *': 'सेवा के वर्ष / अनुभव *',
  'Account Clearance Tier': 'खाता मंजूरी स्तर',
  'Host / Station Administrator': 'होस्ट / थाना व्यवस्थापक',
  'Field Investigation Officer': 'फील्ड जांच अधिकारी',
  'Legal Counsel & Advocate': 'कानूनी सलाहकार एवं अधिवक्ता',
  'Direct Citizen Complainant': 'प्रत्यक्ष नागरिक शिकायतकर्ता',
  'Account Username *': 'खाता यूज़रनेम *',
  'Choose a unique username': 'एक अद्वितीय यूज़रनेम चुनें',
  'Password *': 'पासवर्ड *',
  'Confirm Password *': 'पासवर्ड की पुष्टि करें *',
  'Re-enter your password': 'अपना पासवर्ड पुनः दर्ज करें',
  'Identity Proof Document *': 'पहचान प्रमाण दस्तावेज़ *',
  'National Identity Card, Passport, or Drivers License (Max 10MB)': 'राष्ट्रीय पहचान पत्र, पासपोर्ट, या ड्राइविंग लाइसेंस (अधिकतम 10MB)',
  'Service ID Card / Police Department ID *': 'सेवा पहचान पत्र / पुलिस विभाग आईडी *',
  'Official Police Service Identification Badge or Card (Max 10MB)': 'आधिकारिक पुलिस सेवा पहचान बैज या कार्ड (अधिकतम 10MB)',
  'Biometric Iris Authentication *': 'बायोमेट्रिक आईरिस प्रमाणीकरण *',
  'Iris Scan Verified': 'आईरिस स्कैन सत्यापित',
  'Perform Iris Scan': 'आईरिस स्कैन करें',
  'Security CAPTCHA *': 'सुरक्षा कैप्चा *',
  'CAPTCHA Verified': 'कैप्चा सत्यापित',
  'Verify CAPTCHA': 'कैप्चा सत्यापित करें',
  'Official Undertaking & Terms *': 'आधिकारिक वचनबद्धता एवं शर्तें *',
  'I hereby solemnly declare that all information provided is accurate and true to the best of my knowledge under penalty of official departmental reprimand and legal perjury.': 'मैं सत्यनिष्ठा से घोषणा करता/करती हूँ कि दी गई सभी जानकारी मेरी सर्वोत्तम जानकारी के अनुसार सही एवं सत्य है।',
  'Register & Approve Account': 'खाता पंजीकृत एवं स्वीकृत करें',
  'Account Registered Successfully': 'खाता सफलतापूर्वक पंजीकृत हुआ',
  'Official Credentials Assigned': 'आधिकारिक क्रेडेंशियल सौंपे गए',
  'Login with New Account': 'नए खाते से लॉगिन करें',
  'Register Another Account': 'दूसरा खाता पंजीकृत करें',
  'Copy Credentials': 'क्रेडेंशियल कॉपी करें',
  'Copied to Clipboard': 'क्लिपबोर्ड पर कॉपी किया गया',
  'Pending Requests': 'लंबित अनुरोध',
  'No Pending Requests': 'कोई लंबित अनुरोध नहीं है',
  'All personnel registrations and access requests have been reviewed and approved.': 'सभी कार्मिक पंजीकरण और पहुंच अनुरोधों की समीक्षा कर स्वीकृति दी जा चुकी है।',
  'Recent Activity Log': 'हालिया गतिविधि लॉग',
  'No recent activities recorded.': 'हाल में कोई गतिविधि दर्ज नहीं की गई।',
  'Active Personnel': 'सक्रिय कार्मिक',
  'Total Officers': 'कुल अधिकारी',
  'Total Hosts': 'कुल होस्ट',
  'Total Advocates': 'कुल अधिवक्ता',
  'Total Victims': 'कुल पीड़ित',
  'Assigned Cases Count': 'आवंटित मामलों की संख्या',
  'Active Suspects Tracked': 'सक्रिय संदिग्ध ट्रैक किए गए',
  'Inter-State Coordination': 'अंतर-राज्यीय समन्वय',
  'High Priority Alerts': 'उच्च प्राथमिकता अलर्ट',
  'Court Hearings Scheduled': 'निर्धारित अदालत सुनवाई',
  'Clearance Level': 'मंजूरी स्तर',
  'Station Jurisdiction': 'थाना क्षेत्राधिकार',
  'Metro Central Division': 'मेट्रो सेंट्रल डिवीजन',
  'Criminal Intelligence Bureau': 'आपराधिक खुफिया ब्यूरो',
  'Law Enforcement Network': 'कानून प्रवर्तन नेटवर्क',
  'Encrypted Channel': 'एन्क्रिप्टेड चैनल',
  'Audit Trail Verified': 'ऑडिट ट्रेल सत्यापित',
  'Quick Actions': 'त्वरित कार्रवाइयां',
  'View Investigation Map': 'जांच मानचित्र देखें',
  'Print Police Dossier': 'पुलिस दस्तावेज़ प्रिंट करें',
  'Manage Assigned Team': 'आवंटित टीम प्रबंधित करें',
  'Assign Field Officers': 'फील्ड अधिकारी नियुक्त करें',
  'Select Officers to Assign': 'नियुक्त करने हेतु अधिकारी चुनें',
  'Assign Team': 'टीम नियुक्त करें',
  'Save Team Assignment': 'टीम नियुक्ति सहेजें',
  'Update Progress Status': 'प्रगति स्थिति अपडेट करें',
  'Mark as Closed / Solved': 'हल / बंद चिह्नित करें',
  'Reopen Case': 'केस पुनः खोलें',
  'Are you sure you want to mark this case as solved?': 'क्या आप सुनिश्चित हैं कि आप इस केस को हल किया हुआ चिह्नित करना चाहते हैं?',
  'This will archive active field tasks and lock official evidence files.': 'यह सक्रिय फील्ड कार्यों को संग्रहीत करेगा और आधिकारिक साक्ष्य फ़ाइलों को लॉक कर देगा।',
  'Confirm Case Solved': 'केस हल होने की पुष्टि करें',
  'Confirm Reopen': 'पुनः खोलने की पुष्टि करें',
  'Are you sure you want to delete this evidence file?': 'क्या आप सुनिश्चित हैं कि आप इस साक्ष्य फ़ाइल को हटाना चाहते हैं?',
  'This action cannot be undone. Evidence hash will be permanently purged from this case dossier.': 'यह कार्रवाई पूर्ववत नहीं की जा सकती। साक्ष्य हैश को इस केस दस्तावेज़ से स्थायी रूप से हटा दिया जाएगा।',
  'Permanently Delete': 'स्थायी रूप से हटाएं',
  'Cancel Action': 'कार्रवाई रद्द करें',
  'View Full Dossier': 'पूर्ण दस्तावेज़ देखें',
  'Print Full Case Brief': 'पूर्ण केस ब्रीफ प्रिंट करें',
  'Official Case Report': 'आधिकारिक केस रिपोर्ट',
  'Judicial Presentation Ready': 'न्यायिक प्रस्तुति हेतु तैयार',
  'Evidence Chain of Custody': 'साक्ष्य संरक्षण श्रृंखला (चेन ऑफ कस्टडी)',
  'Digital Hash Verified': 'डिजिटल हैश सत्यापित',
  'Case Closed': 'केस बंद',
  'Case Active': 'केस सक्रिय',
  'Under Judicial Review': 'न्यायिक समीक्षाधीन',
  'Pending Charge Sheet': 'चार्जशीट लंबित',
  'Charge Sheet Submitted': 'चार्जशीट प्रस्तुत',
  'Judicial Verdict Pending': 'न्यायिक फैसला लंबित',
  'Disposed by Court': 'अदालत द्वारा निस्तारित',
  'Acquitted': 'बरी',
  'Convicted': 'दोषी सिद्ध',
  'Bail Granted': 'जमानत स्वीकृत',
  'Bail Denied': 'जमानत अस्वीकृत',
  'Custody Remand': 'हिरासत रिमांड',
  'Judicial Custody': 'न्यायिक हिरासत',
  'Police Custody': 'पुलिस हिरासत',
  'Absconder Notice Issued': 'भगोड़ा नोटिस जारी',
  'Non-Bailable Warrant (NBW)': 'गैर-जमानती वारंट (NBW)',
  'Search Warrant Issued': 'तलाशी वारंट जारी',
  'Lookout Circular (LOC)': 'लुकआउट सर्कुलर (LOC)',
  'Red Corner Notice (Interpol)': 'रेड कॉर्नर नोटिस (इंटरपोल)',
  'Forensic DNA Match': 'फोरेंसिक डीएनए मिलान',
  'Ballistic Report Verified': 'बैलिस्टिक रिपोर्ट सत्यापित',
  'Cyber IP Trace Completed': 'साइबर आईपी ट्रेस पूर्ण',
  'CCTV Facial Recognition Confirmed': 'सीसीटीवी चेहरे की पहचान पुष्ट',
  'Call Detail Records (CDR) Analyzed': 'कॉल डिटेल रिकॉर्ड (CDR) विश्लेषित',
  'Bank Account Frozen': 'बैंक खाता फ्रीज',
  'Property Attached': 'संपत्ति कुर्क',
  'Chargesheet Filed': 'चार्जशीट दाखिल',
  'Chargesheet Pending': 'चार्जशीट लंबित',
  'Supplementary Chargesheet Filed': 'पूरक चार्जशीट दाखिल',
  'Court Appearance Scheduled': 'अदालत में उपस्थिति निर्धारित',
  'Witness Protection Enacted': 'गवाह सुरक्षा लागू',
  'Magistrate Statement 164 CrPC': 'मजिस्ट्रेट बयान 164 दंड प्रक्रिया संहिता',
  'Police Confession Inadmissible': 'पुलिस स्वीकारोक्ति अस्वीकार्य',
  'Judicial Confession Admissible': 'न्यायिक स्वीकारोक्ति स्वीकार्य',
  'Fingerprint Match 99.8%': 'फिंगरप्रिंट मिलान 99.8%',
  'Iris Scan Match Confirmed': 'आईरिस स्कैन मिलान पुष्ट',
  'Identity Verified by Host': 'होस्ट द्वारा पहचान सत्यापित',
  'Access Granted': 'पहुंच स्वीकृत',
  'Access Restricted': 'पहुंच प्रतिबंधित',
  'Session Expired': 'सत्र समाप्त',
  'Re-authenticate Required': 'पुनः प्रमाणीकरण आवश्यक',
  'Security Clearance Required': 'सुरक्षा मंजूरी आवश्यक',
  'Officer Not Found': 'अधिकारी नहीं मिला',
  'Case Not Found': 'केस नहीं मिला',
  'Suspect Not Found': 'संदिग्ध नहीं मिला',
  'Evidence Not Found': 'साक्ष्य नहीं मिला',
  'Update Successful': 'सफलतापूर्वक अपडेट किया गया',
  'Case Updated Successfully': 'केस सफलतापूर्वक अपडेट किया गया',
  'Evidence Uploaded Successfully': 'साक्ष्य सफलतापूर्वक अपलोड हुआ',
  'Suspect Linked Successfully': 'संदिग्ध सफलतापूर्वक लिंक हुआ',
  'Hearing Date Updated Successfully': 'सुनवाई तिथि सफलतापूर्वक अपडेट हुई',
  'APB Dispatched Successfully': 'एपीबी सफलतापूर्वक प्रेषित हुआ',
  'Notification Sent': 'सूचना भेजी गई',
  'Password Updated': 'पासवर्ड अपडेट किया गया',
  'Profile Updated': 'प्रोफ़ाइल अपडेट की गई',
  'Language Switched to Hindi': 'भाषा बदलकर हिन्दी की गई',
  'Language Switched to English': 'भाषा बदलकर अंग्रेज़ी की गई',
  'Confirm Password Match': 'पासवर्ड मिलान की पुष्टि करें',
  'Passwords do not match': 'पासवर्ड मेल नहीं खाते हैं',
  'Password is too weak': 'पासवर्ड बहुत कमजोर है',
  'Password must contain at least 8 characters': 'पासवर्ड में कम से कम 8 वर्ण होने चाहिए',
  'Password must contain an uppercase letter': 'पासवर्ड में कम से कम एक बड़ा अक्षर (A-Z) होना चाहिए',
  'Password must contain a lowercase letter': 'पासवर्ड में कम से कम एक छोटा अक्षर (a-z) होना चाहिए',
  'Password must contain a number': 'पासवर्ड में कम से कम एक संख्या (0-9) होनी चाहिए',
  'Password must contain a special character': 'पासवर्ड में कम से कम एक विशेष वर्ण (!@#$%^&*) होना चाहिए',
  'Weak': 'कमजोर',
  'Fair': 'सामान्य',
  'Good': 'अच्छा',
  'Strong': 'मजबूत',
  'Very Strong': 'अति-मजबूत',
  'Password Strength': 'पासवर्ड की मजबूती',
  'Click here to refresh CAPTCHA': 'कैप्चा रीफ्रेश करने के लिए यहाँ क्लिक करें',
  'Incorrect CAPTCHA code': 'गलत कैप्चा कोड',
  'Please enter matching CAPTCHA': 'कृपया सही कैप्चा दर्ज करें',
  'Iris scanner ready': 'आईरिस स्कैनर तैयार है',
  'Looking for face & retina...': 'चेहरा एवं रेटिना स्कैन जारी...',
  'Blink slowly into the camera': 'कैमरे की ओर धीरे-धीरे पलकें झपकाएं',
  'Retinal pattern match confirmed': 'रेटिना पैटर्न मिलान पुष्ट हुआ',
  'Iris scan successful': 'आईरिस स्कैन सफल रहा',
  'Iris scan failed. Please try again.': 'आईरिस स्कैन विफल रहा। कृपया पुनः प्रयास करें।',
  'Camera access denied': 'कैमरा पहुंच अस्वीकृत',
  'Camera permission is required for biometric iris verification': 'बायोमेट्रिक आईरिस सत्यापन हेतु कैमरे की अनुमति आवश्यक है',
  'Use Simulator Mode': 'सिम्युलेटर मोड का उपयोग करें',
  'Simulate Iris Verification': 'आईरिस सत्यापन सिम्युलेट करें',
  'Scanning in progress...': 'स्कैनिंग जारी है...',
  'Match Score:': 'मिलान स्कोर:',
  'Biometric Template Stored': 'बायोमेट्रिक टेम्पलेट सहेजा गया',
  'AES-256 Encrypted': 'AES-256 एन्क्रिप्टेड',
  'Sha-256 Checksum:': 'Sha-256 चेकसम:',
  'Tamper Evident': 'छेड़छाड़ रोधी',
  'Court Session Scheduled': 'अदालत सत्र निर्धारित',
  'Room No:': 'कमरा संख्या:',
  'Bench:': 'पीठ (बेंच):',
  'Presiding Judge:': 'पीठासीन न्यायाधीश:',
  'Public Prosecutor:': 'लोक अभियोजक:',
  'Defense Counsel:': 'बचाव पक्ष के वकील:',
  'Court Clerk:': 'न्यायालय लिपिक:',
  'Stenographer:': 'आशुलिपिक (स्टेनोग्राफर):',
  'Judicial Magistrate First Class': 'न्यायिक मजिस्ट्रेट प्रथम श्रेणी',
  'Chief Judicial Magistrate (CJM)': 'मुख्य न्यायिक मजिस्ट्रेट (CJM)',
  'Sessions Judge': 'सत्र न्यायाधीश',
  'Special CBI Court': 'विशेष सीबीआई अदालत',
  'High Court of Judicature': 'उच्च न्यायालय',
  'Supreme Court of India': 'भारत का सर्वोच्च न्यायालय',
  'National Crime Records Bureau (NCRB)': 'राष्ट्रीय अपराध रिकॉर्ड ब्यूरो (NCRB)',
  'Crime and Criminal Tracking Network & Systems (CCTNS)': 'अपराध एवं आपराधिक ट्रैकिंग नेटवर्क व प्रणाली (CCTNS)',
  'State Police Headquarters': 'राज्य पुलिस मुख्यालय',
  'District Police Office': 'जिला पुलिस कार्यालय',
  'Sub-Divisional Police Office': 'उप-विभागीय पुलिस कार्यालय',
  'Police Station': 'पुलिस स्टेशन / थाना',
  'Police Outpost / Chowki': 'पुलिस चौकी',
  'Control Room': 'नियंत्रण कक्ष (कंट्रोल रूम)',
  'Dial 112 Emergency': 'डायल 112 आपातकालीन',
  'Cyber Helpline 1930': 'साइबर हेल्पलाइन 1930',
  'Women Helpline 1090': 'महिला हेल्पलाइन 1090',
  'Childline 1098': 'चाइल्डलाइन 1098',
  'Senior Citizen Helpline': 'वरिष्ठ नागरिक हेल्पलाइन',
  'Ambulance 108': 'एंबुलेंस 108',
  'Fire Service 101': 'अग्निशमन सेवा 101',
  'Emergency SOS Dispatched': 'आपातकालीन एसओएस प्रेषित',
  'GPS Coordinates:': 'जीपीएस निर्देशांक:',
  'Live Location Ping': 'लाइव स्थान पिंग',
  'Nearby Patrol Units:': 'निकटतम गश्ती दल:',
  'Patrol Vehicle No:': 'गश्ती वाहन संख्या:',
  'Estimated Time of Arrival (ETA):': 'पहुंचने का अनुमानित समय (ETA):',
  'Officer on Duty:': 'ड्यूटी पर तैनात अधिकारी:',
  'Radio Call Sign:': 'रेडियो कॉल साइन:',
  'Frequency:': 'आवृत्ति (फ्रीक्वेंसी):',
  'Channel 4 Police Tactical': 'चैनल 4 पुलिस सामरिक',
  'Broadcast Alert to All Units': 'सभी इकाइयों को अलर्ट प्रसारित करें',
  'APB Status: Active': 'एपीबी स्थिति: सक्रिय',
  'APB Status: Resolved': 'एपीबी स्थिति: हल',
  'APB Status: Cancelled': 'एपीबी स्थिति: रद्द',
  'Suspect Last Seen:': 'संदिग्ध अंतिम बार देखा गया:',
  'Height:': 'कद / ऊंचाई:',
  'Build:': 'शारीरिक बनावट:',
  'Complexion:': 'रंग-रूप:',
  'Identifying Marks / Tattoos:': 'पहचान चिह्न / टैटू:',
  'Clothing Description:': 'कपड़ों का विवरण:',
  'Vehicle Make & Model:': 'वाहन निर्माण एवं मॉडल:',
  'Registration Plate:': 'पंजीकरण नंबर प्लेट:',
  'Color:': 'रंग:',
  'Direction of Travel:': 'यात्रा की दिशा:',
  'Armed & Dangerous': 'सशस्त्र एवं खतरनाक',
  'Do Not Approach': 'पास न जाएं / अकेले न रोकें',
  'Call Police Immediately': 'तुरंत पुलिस को सूचित करें',
  'Reward Offered:': 'घोषित इनाम:',
  'Confidential Informant Tip': 'गोपनीय मुखबिर सूचना',
  'Tip Received': 'सूचना प्राप्त हुई',
  'Tip Verified': 'सूचना सत्यापित',
  'Raid Executed': 'छापेमारी की गई',
  'Suspect Apprehended': 'संदिग्ध गिरफ्तार',
  'Weapons Seized': 'हथियार जब्त',
  'Contraband Recovered': 'प्रतिबंधित सामग्री बरामद',
  'Stolen Property Returned': 'चोरी की संपत्ति वापस की गई',
  'Victim Assisted': 'पीड़ित को सहायता प्रदान की गई',
  'Medical Aid Administered': 'चिकित्सा सहायता प्रदान की गई',
  'Hospital Remand': 'अस्पताल रिमांड',
  'Post Mortem Report': 'पोस्टमार्टम रिपोर्ट',
  'Inquest Report 174 CrPC': 'पंचनामा रिपोर्ट 174 दंड प्रक्रिया संहिता',
  'Panchnama Witnesses': 'पंचनामा गवाह',
  'Seizure Memo Prepared': 'जब्ती पत्र तैयार',
  'Arrest Memo Signed': 'गिरफ्तारी ज्ञापन हस्ताक्षरित',
  'Intimation to Relative Sent': 'परिजन को सूचना भेजी गई',
  'Legal Aid Provided': 'कानूनी सहायता प्रदान की गई',
  'Free Legal Aid Authorized': 'निःशुल्क कानूनी सहायता अधिकृत',
  'Bar Council ID:': 'बार काउंसिल आईडी:',
  'Enrolment Number:': 'नामांकन संख्या:',
  'Practice Area:': 'वकालत का क्षेत्र:',
  'Criminal Law': 'आपराधिक कानून (क्रिमिनल लॉ)',
  'Constitutional Law': 'संवैधानिक कानून',
  'Cyber Law': 'साइबर कानून',
  'Corporate & White Collar Crime': 'कॉर्पोरेट एवं व्हाइट कॉलर अपराध',
  'Civil Law': 'दीवानी कानून (सिविल लॉ)',
  'Human Rights Defense': 'मानवाधिकार रक्षा',
  'Vakalatnama Filed': 'वकालतनामा दाखिल',
  'Bail Application Pending': 'जमानत याचिका लंबित',
  'Anticipatory Bail Filed': 'अग्रिम जमानत याचिका दाखिल',
  'Regular Bail Granted': 'नियमित जमानत स्वीकृत',
  'Interim Relief Granted': 'अंतरिम राहत स्वीकृत',
  'Writ Petition Lodged': 'रिट याचिका दर्ज',
  'Quashing Petition 482 CrPC': 'निरस्तीकरण याचिका 482 दंड प्रक्रिया संहिता',
  'Stay Order Granted': 'स्थगन आदेश (स्टे ऑर्डर) स्वीकृत',
  'Summons Issued': 'समन जारी',
  'Warrant Issued': 'वारंट जारी',
  'Proclamation Issued 82 CrPC': 'उद्घोषणा जारी 82 दंड प्रक्रिया संहिता',
  'Attachment of Property 83 CrPC': 'संपत्ति की कुर्की 83 दंड प्रक्रिया संहिता',
  'Evidence Tampering Allegation': 'साक्ष्य से छेड़छाड़ का आरोप',
  'Witness Hostile': 'गवाह मुकरा (होस्टाइल)',
  'Cross Examination Completed': 'प्रति-परीक्षा (क्रॉस एग्जामिनेशन) पूर्ण',
  'Final Arguments Heard': 'अंतिम बहस सुनी गई',
  'Judgment Reserved': 'फैसला सुरक्षित रखा गया',
  'Order Pronounced': 'आदेश सुनाया गया',
  'Appeal Filed': 'अपील दाखिल',
  'Certified Copy Applied': 'प्रमाणित प्रति हेतु आवेदन किया गया',
  'Certified Copy Delivered': 'प्रमाणित प्रति प्रदान की गई',
  'File Archived in Judicial Records Room': 'न्यायिक रिकॉर्ड रूम में फ़ाइल संग्रहीत'
}

# Add all remaining clean missing strings with automatic fallback translation
with open("/tmp/clean_missing.json") as f:
    clean_missing = json.load(f)

# Auto-translated words for word-level coverage
WORD_EXPANSIONS = {
  'ACCESS': 'पहुंच',
  'AES': 'एईएस (AES)',
  'AM': 'पूर्वाह्न (AM)',
  'PM': 'अपराह्न (PM)',
  'APB': 'एपीबी (APB)',
  'APBs': 'एपीबी (APBs)',
  'AUTHORIZED': 'अधिकृत',
  'Access': 'पहुंच',
  'Accomplice': 'सह-अपराधी',
  'Account': 'खाता',
  'Act': 'अधिनियम',
  'Action': 'कार्रवाई',
  'Activation': 'सक्रियण',
  'Active': 'सक्रिय',
  'Add': 'जोड़ें',
  'Additional': 'अतिरिक्त',
  'Address': 'पता',
  'Administrator': 'व्यवस्थापक',
  'Advocate': 'अधिवक्ता',
  'Advocates': 'अधिवक्ता',
  'Age': 'आयु',
  'Alarms': 'अलार्म',
  'Alert': 'अलर्ट',
  'Alerts': 'अलर्ट',
  'All': 'सभी',
  'Allegation': 'आरोप',
  'Allegations': 'आरोप',
  'Alleged': 'कथित',
  'Allotted': 'आवंटित',
  'Alternate': 'वैकल्पिक',
  'Ambulance': 'एंबुलेंस',
  'Analysis': 'विश्लेषण',
  'Apple': 'एप्पल',
  'Applicant': 'आवेदक',
  'Apprehension': 'धरपकड़',
  'Approval': 'स्वीकृति',
  'Approvals': 'स्वीकृतियां',
  'Approved': 'स्वीकृत',
  'Approving': 'स्वीकृत किया जा रहा है',
  'Area': 'क्षेत्र',
  'Armed': 'सशस्त्र',
  'Arms': 'हथियार',
  'Arrest': 'गिरफ्तारी',
  'Arson': 'आगजनी',
  'Assign': 'नियुक्त करें',
  'Assigned': 'आवंटित',
  'Assigning': 'नियुक्ति जारी',
  'Attachment': 'संलग्नक',
  'Attack': 'हमला',
  'Audio': 'ऑडियो',
  'Audit': 'ऑडिट',
  'Authentication': 'प्रमाणीकरण',
  'Authorized': 'अधिकृत',
  'Auto': 'स्वतः',
  'Automated': 'स्वचालित',
  'Average': 'औसत',
  'Awaiting': 'प्रतीक्षारत',
  'Background': 'पृष्ठभूमि',
  'Badge': 'बैज',
  'Bail': 'जमानत',
  'Bailed': 'जमानत पर',
  'Bank': 'बैंक',
  'Basic': 'बुनियादी',
  'Bench': 'पीठ',
  'Binary': 'बाइनरी',
  'Biometric': 'बायोमेट्रिक',
  'Biometrics': 'बायोमेट्रिक्स',
  'Blackmail': 'ब्लैकमेल',
  'Blood': 'रक्त',
  'Branch': 'शाखा',
  'Brief': 'ब्रीफ',
  'Briefs': 'ब्रीफ',
  'Bright': 'ब्राइट',
  'Broadcast': 'प्रसारण',
  'Building': 'भवन',
  'Bulletin': 'बुलेटिन',
  'Bulletins': 'बुलेटिन',
  'Burglary': 'सेंधमारी',
  'Calendar': 'कैलेंडर',
  'Cancel': 'रद्द करें',
  'Cancelled': 'रद्द',
  'Captcha': 'कैप्चा',
  'Case': 'केस',
  'Cases': 'मामले',
  'Category': 'श्रेणी',
  'Caution': 'सावधानी',
  'Cell': 'प्रकोष्ठ',
  'Center': 'केंद्र',
  'Central': 'केंद्रीय',
  'Certificate': 'प्रमाणपत्र',
  'Chargesheet': 'चार्जशीट',
  'Chart': 'चार्ट',
  'Check': 'जांचें',
  'Citizen': 'नागरिक',
  'Citizens': 'नागरिक',
  'City': 'शहर',
  'Civil': 'दीवानी',
  'Clear': 'साफ़ करें',
  'Clearance': 'मंजूरी',
  'Cleared': 'दोषमुक्त',
  'Clerk': 'लिपिक',
  'Click': 'क्लिक करें',
  'Close': 'बंद करें',
  'Closed': 'बंद',
  'Code': 'कोड',
  'Command': 'कमान',
  'Complainant': 'शिकायतकर्ता',
  'Complainants': 'शिकायतकर्ता',
  'Complaint': 'शिकायत',
  'Complaints': 'शिकायतें',
  'Complete': 'पूर्ण',
  'Completed': 'पूर्ण',
  'Confirm': 'पुष्टि करें',
  'Confirmed': 'पुष्ट',
  'Connect': 'जोड़ें',
  'Connected': 'जुड़ा हुआ',
  'Constable': 'कांस्टेबल',
  'Contact': 'संपर्क',
  'Control': 'नियंत्रण',
  'Convicted': 'दोषी',
  'Coordination': 'समन्वय',
  'Copy': 'कॉपी',
  'Counsel': 'सलाहकार',
  'Countdown': 'उलटी गिनती',
  'Court': 'अदालत',
  'Courts': 'अदालतें',
  'Create': 'बनाएं',
  'Created': 'बनाया गया',
  'Crime': 'अपराध',
  'Crimes': 'अपराध',
  'Criminal': 'आपराधिक',
  'Critical': 'अति-गंभीर',
  'Custody': 'हिरासत',
  'Cyber': 'साइबर',
  'Daily': 'दैनिक',
  'Dark': 'डार्क',
  'Dashboard': 'डैशबोर्ड',
  'Data': 'डेटा',
  'Date': 'तारीख',
  'Day': 'दिन',
  'Days': 'दिन',
  'Deadline': 'समयसीमा',
  'Decision': 'निर्णय',
  'Declare': 'घोषित करें',
  'Defend': 'बचाव करें',
  'Defense': 'बचाव पक्ष',
  'Delete': 'हटाएं',
  'Deleted': 'हटाया गया',
  'Demo': 'डेमो',
  'Department': 'विभाग',
  'Departmental': 'विभागीय',
  'Departments': 'विभाग',
  'Description': 'विवरण',
  'Designation': 'पदनाम',
  'Desk': 'डेस्क',
  'Details': 'विवरण',
  'Dial': 'डायल करें',
  'Digital': 'डिजिटल',
  'Direct': 'प्रत्यक्ष',
  'Director': 'निदेशक',
  'Dispatch': 'प्रेषण',
  'Dispatched': 'प्रेषित',
  'Distribution': 'वितरण',
  'District': 'जिला',
  'Division': 'मंडल',
  'Document': 'दस्तावेज़',
  'Documents': 'दस्तावेज़',
  'Download': 'डाउनलोड',
  'Downloaded': 'डाउनलोड किया गया',
  'Dossier': 'दस्तावेज़',
  'Drive': 'ड्राइव',
  'Edit': 'संपादित करें',
  'Edited': 'संपादित',
  'Email': 'ईमेल',
  'Emergency': 'आपातकालीन',
  'Encrypted': 'एन्क्रिप्टेड',
  'Encryption': 'एन्क्रिप्शन',
  'Enrol': 'नामांकन करें',
  'Enrolled': 'नामांकित',
  'Enrolment': 'नामांकन',
  'Enter': 'दर्ज करें',
  'Evidence': 'साक्ष्य',
  'Exhibit': 'प्रदर्श',
  'Exhibits': 'प्रदर्श',
  'Experience': 'अनुभव',
  'Expert': 'विशेषज्ञ',
  'Export': 'निर्यात',
  'Extortion': 'जबरन वसूली',
  'Eye': 'आईरिस / आंख',
  'FIR': 'एफआईआर',
  'False': 'असत्य',
  'Feedback': 'प्रतिक्रिया',
  'Female': 'महिला',
  'Field': 'फील्ड',
  'File': 'फ़ाइल',
  'Files': 'फ़ाइलें',
  'Filter': 'फ़िल्टर',
  'Filtered': 'फ़िल्टर किया गया',
  'Final': 'अंतिम',
  'Fingerprint': 'फिंगरप्रिंट',
  'Flash': 'फ्लैश',
  'Forensic': 'फोरेंसिक',
  'Form': 'फॉर्म',
  'Fraud': 'धोखाधड़ी',
  'Full': 'पूरा',
  'Gender': 'लिंग',
  'General': 'सामान्य',
  'Generate': 'उत्पन्न करें',
  'Generated': 'उत्पन्न',
  'Graph': 'ग्राफ',
  'Group': 'समूह',
  'Guard': 'रक्षक',
  'Hash': 'हैश',
  'Head': 'प्रमुख',
  'Headquarters': 'मुख्यालय',
  'Hearing': 'सुनवाई',
  'Hearings': 'सुनवाई',
  'Heatmap': 'हीटमैप',
  'Help': 'सहायता',
  'High': 'उच्च',
  'History': 'इतिहास',
  'Homicide': 'हत्या',
  'Hospital': 'अस्पताल',
  'Host': 'होस्ट',
  'Hour': 'घंटा',
  'Hours': 'घंटे',
  'ID': 'आईडी',
  'Identification': 'पहचान',
  'Identify': 'पहचानें',
  'Identity': 'पहचान',
  'Image': 'छवि',
  'Images': 'छवियां',
  'Incident': 'घटना',
  'Incidents': 'घटनाएं',
  'Info': 'जानकारी',
  'Information': 'सूचना',
  'Informant': 'मुखबिर',
  'Input': 'इनपुट',
  'Inspect': 'निरीक्षण करें',
  'Inspector': 'इंस्पेक्टर',
  'Intelligence': 'खुफिया',
  'Inter-State': 'अंतर-राज्यीय',
  'Interrogation': 'पूछताछ',
  'Investigate': 'जांच करें',
  'Investigation': 'जांच',
  'Investigations': 'जांच',
  'Iris': 'आईरिस',
  'Issue': 'जारी करें',
  'Issued': 'जारी किया गया',
  'Judicial': 'न्यायिक',
  'Jurisdiction': 'क्षेत्राधिकार',
  'Justice': 'न्याय',
  'Key': 'कुंजी',
  'Kidnapping': 'अपहरण',
  'Lab': 'प्रयोगशाला',
  'Last': 'अंतिम',
  'Law': 'कानून',
  'Ledger': 'बहीखाता',
  'Legal': 'कानूनी',
  'Level': 'स्तर',
  'License': 'लाइसेंस',
  'Limit': 'सीमा',
  'Limited': 'सीमित',
  'Line': 'लाइन',
  'Link': 'लिंक',
  'Linked': 'जुड़ा हुआ',
  'List': 'सूची',
  'Live': 'लाइव',
  'Load': 'लोड',
  'Location': 'स्थान',
  'Lock': 'लॉक',
  'Locked': 'लॉक किया गया',
  'Log': 'लॉग',
  'Logging': 'लॉगिंग',
  'Login': 'लॉगिन',
  'Logout': 'लॉगआउट',
  'Logs': 'लॉग',
  'Low': 'कम',
  'Magistrate': 'मजिस्ट्रेट',
  'Male': 'पुरुष',
  'Manage': 'प्रबंधित करें',
  'Management': 'प्रबंधन',
  'Manager': 'प्रबंधक',
  'Map': 'मानचित्र',
  'Mark': 'चिह्नित करें',
  'Marked': 'चिह्नित',
  'Marks': 'चिह्न',
  'Match': 'मिलान',
  'Matched': 'मेल खाया',
  'Matching': 'मेल खाता',
  'Matrix': 'मैट्रिक्स',
  'Medical': 'चिकित्सा',
  'Medium': 'मध्यम',
  'Member': 'सदस्य',
  'Members': 'सदस्य',
  'Menu': 'मेनू',
  'Message': 'संदेश',
  'Messages': 'संदेश',
  'Metadata': 'मेटाडेटा',
  'Milestone': 'मील का पत्थर',
  'Milestones': 'मील के पत्थर',
  'Minute': 'मिनट',
  'Minutes': 'मिनट',
  'Missing': 'लापता',
  'Mobile': 'मोबाइल',
  'Mode': 'मोड',
  'Model': 'मॉडल',
  'Month': 'महीना',
  'Monthly': 'मासिक',
  'More': 'अधिक',
  'Murder': 'कत्ल',
  'Name': 'नाम',
  'Narcotics': 'मादक पदार्थ',
  'National': 'राष्ट्रीय',
  'Network': 'नेटवर्क',
  'New': 'नया',
  'Next': 'अगला',
  'No': 'नहीं',
  'None': 'कोई नहीं',
  'Normal': 'सामान्य',
  'North': 'उत्तर',
  'Notice': 'सूचना',
  'Notification': 'सूचना',
  'Notifications': 'सूचनाएं',
  'Number': 'संख्या',
  'Numbers': 'संख्याएं',
  'Offense': 'अपराध',
  'Offenses': 'अपराध',
  'Office': 'कार्यालय',
  'Officer': 'अधिकारी',
  'Officers': 'अधिकारी',
  'Official': 'आधिकारिक',
  'Online': 'ऑनलाइन',
  'Open': 'खोलें',
  'Order': 'आदेश',
  'Other': 'अन्य',
  'Others': 'अन्य',
  'Overview': 'अवलोकन',
  'Page': 'पृष्ठ',
  'Panel': 'पैनल',
  'Password': 'पासवर्ड',
  'Patrol': 'गश्त',
  'Pending': 'लंबित',
  'Person': 'व्यक्ति',
  'Personal': 'व्यक्तिगत',
  'Personnel': 'कार्मिक',
  'Phone': 'फ़ोन',
  'Photo': 'तस्वीर',
  'Photograph': 'तस्वीर',
  'Photos': 'तस्वीरें',
  'Plate': 'नंबर प्लेट',
  'Police': 'पुलिस',
  'Portal': 'पोर्टल',
  'Precinct': 'थाना क्षेत्र',
  'Preview': 'पूर्वावलोकन',
  'Previous': 'पिछला',
  'Print': 'प्रिंट',
  'Priority': 'प्राथमिकता',
  'Process': 'प्रक्रिया',
  'Profile': 'प्रोफ़ाइल',
  'Progress': 'प्रगति',
  'Proof': 'प्रमाण',
  'Protocol': 'प्रोटोकॉल',
  'Public': 'सार्वजनिक',
  'Query': 'क्वेरी',
  'Quick': 'त्वरित',
  'Radio': 'रेडियो',
  'Raid': 'छापेमारी',
  'Rank': 'पद',
  'Recent': 'हालिया',
  'Record': 'रिकॉर्ड',
  'Records': 'रिकॉर्ड',
  'Recovered': 'बरामद',
  'Reference': 'संदर्भ',
  'Refresh': 'ताज़ा करें',
  'Register': 'पंजीकृत करें',
  'Registered': 'पंजीकृत',
  'Registration': 'पंजीकरण',
  'Reject': 'अस्वीकार करें',
  'Rejected': 'अस्वीकृत',
  'Release': 'रिहाई',
  'Remarks': 'टिप्पणियां',
  'Remove': 'हटाएं',
  'Report': 'रिपोर्ट',
  'Reports': 'रिपोर्टें',
  'Repository': 'रिपॉजिटरी',
  'Request': 'अनुरोध',
  'Requests': 'अनुरोध',
  'Required': 'आवश्यक',
  'Reset': 'रीसेट',
  'Resolve': 'हल करें',
  'Resolved': 'हल किया गया',
  'Response': 'प्रतिक्रिया',
  'Restricted': 'प्रतिबंधित',
  'Result': 'परिणाम',
  'Results': 'परिणाम',
  'Review': 'समीक्षा',
  'Reviewed': 'समीक्षित',
  'Risk': 'जोखिम',
  'Robbery': 'डकैती',
  'Role': 'भूमिका',
  'Roles': 'भूमिकाएं',
  'Routine': 'सामान्य',
  'Save': 'सहेजें',
  'Saved': 'सहेजा गया',
  'Scan': 'स्कैन',
  'Scanner': 'स्कैनर',
  'Schedule': 'कार्यसूची',
  'Scheduled': 'निर्धारित',
  'Scene': 'स्थल',
  'Score': 'स्कोर',
  'Search': 'खोजें',
  'Second': 'सेकंड',
  'Seconds': 'सेकंड',
  'Section': 'अनुभाग',
  'Secure': 'सुरक्षित',
  'Secured': 'सुरक्षित किया गया',
  'Security': 'सुरक्षा',
  'Select': 'चुनें',
  'Selected': 'चयनित',
  'Send': 'भेजें',
  'Sent': 'भेजा गया',
  'Service': 'सेवा',
  'Session': 'सत्र',
  'Set': 'तय करें',
  'Settings': 'सेटिंग्स',
  'Share': 'साझा करें',
  'Show': 'दिखाएं',
  'Side': 'पक्ष',
  'Sidebar': 'साइडबार',
  'Sign': 'हस्ताक्षर',
  'Signal': 'सिग्नल',
  'Size': 'आकार',
  'Slip': 'पर्ची',
  'Solved': 'हल किया गया',
  'South': 'दक्षिण',
  'Special': 'विशेष',
  'State': 'राज्य',
  'States': 'राज्य',
  'Station': 'थाना',
  'Status': 'स्थिति',
  'Step': 'चरण',
  'Steps': 'चरण',
  'Submit': 'सबमिट करें',
  'Submitted': 'सबमिट किया गया',
  'Success': 'सफल',
  'Successful': 'सफल',
  'Successfully': 'सफलतापूर्वक',
  'Summary': 'सारांश',
  'Superintendent': 'अधीक्षक',
  'Supervisor': 'पर्यवेक्षक',
  'Suspect': 'संदिग्ध',
  'Suspects': 'संदिग्ध',
  'System': 'प्रणाली',
  'Table': 'तालिका',
  'Tag': 'टैग',
  'Target': 'लक्ष्य',
  'Task': 'कार्य',
  'Tasks': 'कार्य',
  'Team': 'टीम',
  'Teams': 'टीमें',
  'Terms': 'शर्तें',
  'Theft': 'चोरी',
  'Theme': 'थीम',
  'Time': 'समय',
  'Timeline': 'समयरेखा',
  'Timeout': 'समय समाप्त',
  'Tip': 'टिप / सूचना',
  'Title': 'शीर्षक',
  'Today': 'आज',
  'Toggle': 'बदलें',
  'Total': 'कुल',
  'Track': 'ट्रैक करें',
  'Tracking': 'ट्रैकिंग',
  'Traffic': 'यातायात',
  'Trail': 'ट्रेल',
  'Transparency': 'पारदर्शिता',
  'Trend': 'प्रवृत्ति',
  'Trends': 'प्रवृत्तियां',
  'True': 'सत्य',
  'Type': 'प्रकार',
  'Types': 'प्रकार',
  'Unassigned': 'अनावंटित',
  'Under': 'के अंतर्गत',
  'Unit': 'इकाई',
  'Units': 'इकाइयां',
  'Unknown': 'अज्ञात',
  'Unlock': 'अनलॉक',
  'Unsolved': 'अनसुलझा',
  'Update': 'अपडेट',
  'Updated': 'अपडेट किया गया',
  'Updates': 'अपडेट',
  'Upload': 'अपलोड',
  'Uploaded': 'अपलोड किया गया',
  'Urgency': 'तात्कालिकता',
  'Urgent': 'अति-आवश्यक',
  'User': 'उपयोगकर्ता',
  'Username': 'यूज़रनेम',
  'Users': 'उपयोगकर्ता',
  'Valid': 'वैध',
  'Validate': 'सत्यापित करें',
  'Vehicle': 'वाहन',
  'Verdict': 'फैसला',
  'Verification': 'सत्यापन',
  'Verified': 'सत्यापित',
  'Verify': 'सत्यापित करें',
  'Victim': 'पीड़ित',
  'Victims': 'पीड़ित',
  'Video': 'वीडियो',
  'View': 'देखें',
  'Views': 'दृश्य',
  'Wanted': 'वांछित',
  'Warning': 'चेतावनी',
  'Warrant': 'वारंट',
  'Watch': 'देखें',
  'Week': 'सप्ताह',
  'Weeks': 'सप्ताह',
  'Welcome': 'स्वागत है',
  'West': 'पश्चिम',
  'Witness': 'गवाह',
  'Witnesses': 'गवाह',
  'Year': 'वर्ष',
  'Years': 'वर्ष',
  'Yes': 'हाँ',
  'Zone': 'क्षेत्र'
}

with open("/tmp/new_translations.json", "w") as f:
    json.dump(NEW_TRANSLATIONS, f, indent=2, ensure_ascii=False)

with open("/tmp/word_expansions.json", "w") as f:
    json.dump(WORD_EXPANSIONS, f, indent=2, ensure_ascii=False)

print(f"Generated {len(NEW_TRANSLATIONS)} new phrase translations.")
print(f"Generated {len(WORD_EXPANSIONS)} word expansions.")
